#Author: Vani.Puranam@CVSHealth.com
@BeautyClubRelaunch
Feature: View Customer Beauty Club Details

  @Web @Mobile @POS @Smoke @Regression
  Scenario Outline: View Customer Beauty Club Details in DashBoard
    Given <scenario>
    And I use my Extra Card <xtra_card_nbr>
    When I view Beauty Club Details in DashBoard for my card
    Then I see the Beauty Club Rewards
    And I see my Beauty Club enrollment status as <enrolled>
    And I see my Beauty Club Free Item Campaign Id as <free_campaign_id> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Campaign WebDescription as <web_description> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Campaign End Date as <campaign_end_date> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Offer Limit Reached as <offer_limit_reached> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Threshold Type Code as <threshold_type_code> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item First Threshold as <first_threshold> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Points required to get next coupon as <points_to_next_threshold> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Points Progress as <points_progress> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item coupon number as <coupon_number> <both_Campaigns> <earned>
    And I see my Beauty Club percent Campaign Id as <percent_campaign_id> <both_Campaigns> <earned>
    And I see my Beauty Club percent Campaign WebDescription <percent_web_description> <both_Campaigns> <earned>
    And I see my Beauty Club percent Campaign End Date as <percent_campaign_end_date> <both_Campaigns> <earned>
    And I see my Beauty Club percent Offer Limit Reached as <percent_offer_limit_reached> <both_Campaigns> <earned>
    And I see my Beauty Club percent extrabuckRewardsEarned as <extrabuck_rewards_earned> <both_Campaigns> <earned>
    Examples:
      | scenario                                                                                                                                          | xtra_card_nbr | free_campaign_id | percent_campaign_id | web_description    | percent_web_description           | campaign_end_date | percent_campaign_end_date | threshold_type_code | first_threshold | points_to_next_threshold | offer_limit_reached | percent_offer_limit_reached | points_progress | channel | enrolled | extrabuck_rewards_earned | coupon_number | both_Campaigns | earned |
      | "As a BeautyClub Program member I spend on Beauty products and started earning for both free item and 10% Coupons when both Campaigns are Active" | 900058601     | 11111            | 22222               | "Beauty Club 2021" | "10% Off EB Beauty Club campaign" | "nextmonth"       | "2weeks"                  | "D"                 | 30.0            | 15.0                     | "false"             | "false"                     | 15.0            | "WEB"   | "true"   | 8.0                      | 33333         | "Y"            | "Y"    |
      | "As a BeautyClub Program member I spent on Beauty products only for Free item Coupon when both Free item and 10% Campaigns are Active"            | 900058602     | 11111            | 00000               | "Beauty Club 2021" | "null"                            | "nextmonth"       | "null"                    | "D"                 | 30.0            | 5.0                      | "false"             | "null"                      | 25.0            | "WEB"   | "true"   | 000.00                   | 33333         | "Y"            | "Y"    |
      | "As a BeautyClub Program member I spent on Beauty products only for 10% campaign when both Free item and 10% Campaigns are Active"                | 900058603     | 00000            | 22222               | "null"             | "10% Off EB Beauty Club campaign" | "null"            | "2weeks"                  | "null"              | 000.00          | 000.00                   | "null"              | "false"                     | 000.00          | "WEB"   | "true"   | 120.00                   | 00000         | "Y"            | "Y"    |

  @Web @Mobile @POS @Smoke @Regression
  Scenario Outline: View Customer Beauty Club Details in DashBoard
    Given <scenario>
    And I use my Extra Card <xtra_card_nbr>
    When I view Beauty Club Details in DashBoard for my card
    Then I see the Beauty Club Rewards
    And I see my Beauty Club enrollment status as <enrolled>
    And I see my Beauty Club Free Item Campaign Id as <free_campaign_id> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Campaign WebDescription as <web_description> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Campaign End Date as <campaign_end_date> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Threshold Type Code as <threshold_type_code> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item First Threshold as <first_threshold> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Points required to get next coupon as <points_to_next_threshold> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Offer Limit Reached as <offer_limit_reached> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Points Progress as <points_progress> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item coupon number as <coupon_number> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Coupon loadable Indicator as <Free_Loadable> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Coupon loadActualDate as <Free_loadActualDate> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Coupon Description as <free_couponDescription> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Coupon Sequence Number as <free_couponseqnbr> <both_Campaigns> <earned>
    And I see my Beauty Club percent Campaign Id as <percent_campaign_id> <both_Campaigns> <earned>
    And I see my Beauty Club percent Campaign WebDescription <percent_web_description> <both_Campaigns> <earned>
    And I see my Beauty Club percent Campaign End Date as <percent_campaign_end_date> <both_Campaigns> <earned>
    And I see my Beauty Club percent extrabuckRewardsEarned as <extrabuck_rewards_earned> <both_Campaigns> <earned>
    And I see my Beauty Club percent Offer Limit Reached as <percent_offer_limit_reached> <both_Campaigns> <earned>
    And I see my Beauty Club percent Coupon loadable Indicator as <percent_Loadable> <both_Campaigns> <earned>
    And I see my Beauty Club percent Coupon loadActualDate as <percent_loadActualDate> <both_Campaigns> <earned>
    And I see my Beauty Club percent Coupon Issue Date as <percent_couponIssueDate> <both_Campaigns> <earned>
    And I see my Beauty Club percent Coupon Sequence Number as <percent_couponseqnbr> <both_Campaigns> <earned>
    Examples:
      | scenario                                                                                                                                                                                                                  | xtra_card_nbr | free_campaign_id | percent_campaign_id | web_description    | percent_web_description           | campaign_end_date | percent_campaign_end_date | threshold_type_code | first_threshold | points_to_next_threshold | offer_limit_reached | percent_offer_limit_reached | points_progress | channel | enrolled | extrabuck_rewards_earned | coupon_number | percent_coupon_number | Free_Loadable | Free_loadActualDate | free_couponDescription      | percent_Loadable | percent_loadActualDate | percent_couponIssueDate | both_Campaigns | earned | free_couponseqnbr | percent_couponseqnbr |
      | "As a BeautyClub Program member I spend on Beauty products and reached limit for only Free Item Coupon and want to see only Free Item coupon with CpnNbr, Loadable as Y and pts"                                          | 900058604     | 11111            | 00000               | "Beauty Club 2021" | "null"                            | "nextmonth"       | "null"                    | "D"                 | 30.0            | 0.00                     | "true"              | "null"                      | 30.0            | "WEB"   | "true"   | 000.00                   | 33333         | 00000                 | "true"        | "null"              | "Free item for Beauty Club" | "null"           | "null"                 | "null"                  | "N"            | "Y"    | 90005860411111    | 00000                |
      | "As a BeautyClub Program member I spend on Beauty products and reached limit for both Free Item and 10% coupon and want to see Free Item and 10% coupons with CpnNbr, Loadable as Y and pts"                              | 900058605     | 11111            | 22222               | "Beauty Club 2021" | "10% Off EB Beauty Club campaign" | "nextmonth"       | "2weeks"                  | "D"                 | 30.0            | 0.00                     | "true"              | "true"                      | 30.0            | "WEB"   | "true"   | 20.0                     | 33333         | 44444                 | "true"        | "null"              | "Free item for Beauty Club" | "true"           | "null"                 | "today"                 | "Y"            | "Y"    | 90005860511111    | 90005860522222       |
      | "As a BeautyClub Program member I spend on Beauty products and started earning for both Free Item and 10% coupon and want to see Free Item and 10% coupons with CpnNbr and pts"                                           | 900058606     | 11111            | 22222               | "Beauty Club 2021" | "10% Off EB Beauty Club campaign" | "nextmonth"       | "2weeks"                  | "D"                 | 30.0            | 10.0                     | "false"             | "false"                     | 20.0            | "WEB"   | "true"   | 10.0                     | 33333         | 44444                 | "null"        | "null"              | "Free item for Beauty Club" | "null"           | "null"                 | "null"                  | "Y"            | "Y"    | 00000             | 00000                |
      | "As a BeautyClub Program member I spend on Beauty products and started earning for free item when only free item campaign is Active and want to see Free Item Coupon with CpnNbr and pts"                                 | 900058607     | 11111            | 00000               | "Beauty Club 2021" | "null"                            | "nextmonth"       | "null"                    | "D"                 | 30.0            | 25.43                    | "false"             | "null"                      | 4.57            | "WEB"   | "true"   | 000.00                   | 33333         | 00000                 | "null"        | "null"              | "Free item for Beauty Club" | "null"           | "null"                 | "null"                  | "N"            | "Y"    | 00000             | 00000                |
      | "As a BeautyClub Program member I spend on Beauty products and started earning for 10% Coupon and dont want to see loadActualDate, couponIssueDate and couponDescription"                                                 | 900058608     | 00000            | 22222               | "null"             | "10% Off EB Beauty Club campaign" | "null"            | "2weeks"                  | "null"              | 000.00          | 000.00                   | "null"              | "false"                     | 000.00          | "WEB"   | "true"   | 2.0                      | 00000         | 44444                 | "null"        | "null"              | "null"                      | "null"           | "null"                 | "null"                  | "N"            | "Y"    | 00000             | 90005860822222       |
      | "As a BeautyClub Program member I reached limit and earned 10% Coupon and want to see couponSequenceNumber ,couponIssueDate and loadActualDate but dont want to see couponDescription"                                    | 900058609     | 00000            | 22222               | "null"             | "10% Off EB Beauty Club campaign" | "null"            | "2weeks"                  | "null"              | 000.00          | 000.00                   | "null"              | "true"                      | 000.00          | "WEB"   | "true"   | 20.0                     | 00000         | 44444                 | "null"        | "null"              | "null"                      | "false"          | "today"                | "today"                 | "N"            | "Y"    | 00000             | 90005860922222       |
      | "As a BeautyClub Program member I spend on Beauty products and didnt earn points for Free Item Coupon and want to see couponDescription but dont want to see couponIssueDate,loadActualDate"                              | 900058610     | 11111            | 00000               | "Beauty Club 2021" | "null"                            | "nextmonth"       | "null"                    | "D"                 | 30.0            | 30.00                    | "false"             | "null"                      | 0.00            | "WEB"   | "true"   | 000.00                   | 00000         | 00000                 | "null"        | "null"              | "Free item for Beauty Club" | "null"           | "null"                 | "null"                  | "N"            | "N"    | 00000             | 00000                |
      | "As a BeautyClub Program member I spend on Beauty products and started earning points for Free Item Coupon and want to see couponDescription but dont want to see couponIssueDate and loadActualDate"                     | 900058611     | 11111            | 00000               | "Beauty Club 2021" | "null"                            | "nextmonth"       | "null"                    | "D"                 | 30.0            | 5.43                     | "false"             | "null"                      | 24.57           | "WEB"   | "true"   | 000.00                   | 33333         | 00000                 | "null"        | "null"              | "Free item for Beauty Club" | "null"           | "null"                 | "null"                  | "N"            | "Y"    | 00000             | 00000                |
      | "As a BeautyClub Program member I spend on Beauty products and reached limit and earned Free Item Coupon and want to see couponSequenceNumber ,couponDescription and loadActualDate but dont want to see couponIssueDate" | 900058612     | 11111            | 00000               | "Beauty Club 2021" | "null"                            | "nextmonth"       | "null"                    | "D"                 | 30.0            | 0.00                     | "true"              | "null"                      | 30.0            | "WEB"   | "true"   | 000.00                   | 33333         | 00000                 | "false"       | "today"             | "Free item for Beauty Club" | "null"           | "null"                 | "null"                  | "N"            | "Y"    | 90005861211111    | 00000                |
      | "As a BeautyClub Program member I didnt spend on Beauty products for Free Item Coupon and want to see only Free Item Coupon with default response including CpnNbr and no pts"                                            | 900058613     | 11111            | 00000               | "Beauty Club 2021" | "null"                            | "nextmonth"       | "null"                    | "D"                 | 30.0            | 30.00                    | "null"              | "null"                      | 0.00            | "WEB"   | "true"   | 000.00                   | 33333         | 00000                 | "null"        | "null"              | "Free item for Beauty Club" | "null"           | "null"                 | "null"                  | "N"            | "N"    | 00000             | 00000                |
      | "As a BeautyClub Program member I didnt spend on Beauty products for Free Item Coupon and 10% coupon and want to see Free Item Coupon and 10% coupon with default fields with CpnNbr and no pts"                          | 900058614     | 11111            | 22222               | "Beauty Club 2021" | "10% Off EB Beauty Club campaign" | "nextmonth"       | "2weeks"                  | "D"                 | 30.0            | 30.00                    | "null"              | "null"                      | 0.00            | "WEB"   | "true"   | 0.00                     | 33333         | 44444                 | "null"        | "null"              | "Free item for Beauty Club" | "null"           | "null"                 | "null"                  | "Y"            | "N"    | 00000             | 00000                |

  @Web @Mobile @POS @Smoke @Regression
  Scenario Outline: View Customer Beauty Club Details in DashBoard
    Given <scenario>
    And I use my Extra Card <xtra_card_nbr>
    When I view Beauty Club Details in DashBoard for my card
    Then I see the Beauty Club Rewards
    And I see my Beauty Club enrollment status as <enrolled>
    And I see my Beauty Club Free Item Campaign Id as <free_campaign_id> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Campaign WebDescription as <web_description> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Campaign End Date as <campaign_end_date> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Threshold Type Code as <threshold_type_code> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item First Threshold as <first_threshold> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Points required to get next coupon as <points_to_next_threshold> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Offer Limit Reached as <offer_limit_reached> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Points Progress as <points_progress> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item coupon number as <coupon_number> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Coupon loadable Indicator as <Free_Loadable> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Coupon loadActualDate as <Free_loadActualDate> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Coupon Description as <free_couponDescription> <both_Campaigns> <earned>
    And I see my Beauty Club Free Coupon daysLeft as <days_Left> <both_Campaigns> <earned>
    And I see my Beauty Club Free Coupon freeItemCoupon Flag as <freeItemCoupon_flag> <both_Campaigns> <earned>
    And I see my Beauty Club percent Campaign Id as <percent_campaign_id> <both_Campaigns> <earned>
    And I see my Beauty Club percent Campaign WebDescription <percent_web_description> <both_Campaigns> <earned>
    And I see my Beauty Club percent Campaign End Date as <percent_campaign_end_date> <both_Campaigns> <earned>
    And I see my Beauty Club percent Offer Limit Reached as <percent_offer_limit_reached> <both_Campaigns> <earned>
    And I see my Beauty Club percent extrabuckRewardsEarned as <extrabuck_rewards_earned> <both_Campaigns> <earned>
    And I see my Beauty Club percent Coupon loadable Indicator as <percent_Loadable> <both_Campaigns> <earned>
    And I see my Beauty Club percent Coupon loadActualDate as <percent_loadActualDate> <both_Campaigns> <earned>
    And I see my Beauty Club percent Coupon Issue Date as <percent_couponIssueDate> <both_Campaigns> <earned>
    And I see my Beauty Club percent Coupon freeItemCoupon Flag as <percent_freeItemCoupon_flag> <both_Campaigns> <earned>
    And I see my Beauty Club percent Coupon daysLeft as <percent_days_Left> <both_Campaigns> <earned>
    Examples:
      | scenario                                                                                                                                        | xtra_card_nbr | free_campaign_id | percent_campaign_id | web_description    | percent_web_description           | campaign_end_date | percent_campaign_end_date | threshold_type_code | first_threshold | points_to_next_threshold | offer_limit_reached | percent_offer_limit_reached | points_progress | channel | enrolled | extrabuck_rewards_earned | coupon_number | percent_coupon_number | Free_Loadable | Free_loadActualDate | free_couponDescription | percent_Loadable | percent_loadActualDate | percent_couponIssueDate | freeItemCoupon_flag | days_Left | percent_days_Left | percent_freeItemCoupon_flag | both_Campaigns | earned | free_couponseqnbr | percent_couponseqnbr |
      | "As a BeautyClub Program member I want to see extrabuckRewardsEarned as 0$ when I didn't start earning for 10% Coupon"                          | 900058615     | 00000            | 22222               | "null"             | "10% Off EB Beauty Club campaign" | "null"            | "2weeks"                  | "null"              | 000.00          | 000.00                   | "null"              | "false"                     | 000.00          | "WEB"   | "true"   | 0.0                      | 00000         | 00000                 | "null"        | "null"              | "This Month Gift"      | "null"           | "null"                 | "null"                  | "null"              | 12345     | 2                 | "false"                     | "N"            | "N"    | 00000             | 00000                |
      | "As a BeautyClub Program member I want to see extrabuckRewardsEarned as 10$ when I earned 100pts for 10% Coupon"                                | 900058616     | 00000            | 22222               | "null"             | "10% Off EB Beauty Club campaign" | "null"            | "2weeks"                  | "null"              | 000.00          | 000.00                   | "null"              | "false"                     | 000.00          | "WEB"   | "true"   | 10.0                     | 00000         | 44444                 | "null"        | "null"              | "null"                 | "null"           | "null"                 | "null"                  | "null"              | 12345     | 2                 | "false"                     | "N"            | "Y"    | 00000             | 90005861622222       |
      | "As a BeautyClub Program member I want to see extrabuckRewardsEarned as 20$ and offer LimitReached as true when I earned 201pts for 10% Coupon" | 900058617     | 00000            | 22222               | "null"             | "10% Off EB Beauty Club campaign" | "null"            | "2weeks"                  | "null"              | 000.00          | 000.00                   | "null"              | "true"                      | 000.00          | "WEB"   | "true"   | 20.0                     | 00000         | 44444                 | "null"        | "null"              | "null"                 | "true"           | "null"                 | "today"                 | "null"              | 12345     | 2                 | "false"                     | "N"            | "N"    | 00000             | 90005861722222       |
      | "As a BeautyClub Program member I want to see freeItemCoupon flag as true when Free Item Campaign is active"                                    | 900058618     | 11111            | 00000               | "Beauty Club 2021" | "null"                            | "nextmonth"       | "null"                    | "D"                 | 30.0            | 20.00                    | "true"              | "null"                      | 10.00           | "WEB"   | "true"   | 000.00                   | 00000         | 0000                  | "null"        | "null"              | "null"                 | "null"           | "null"                 | "null"                  | "true"              | 10        | 12345             | "null"                      | "N"            | "Y"    | 00000             | 00000                |
      | "As a BeautyClub Program member I want to see freeItemCoupon flag as false when 10% Campaign is active"                                         | 900058619     | 00000            | 22222               | "null"             | "10% Off EB Beauty Club campaign" | "null"            | "2weeks"                  | "null"              | 000.00          | 000.00                   | "null"              | "false"                     | 000.00          | "WEB"   | "true"   | 0.0                      | 00000         | 00000                 | "null"        | "null"              | "null"                 | "null"           | "null"                 | "null"                  | "null"              | 12345     | 2                 | "false"                     | "N"            | "N"    | 00000             | 00000                |
      | "As a BeautyClub Program member I want to see daysLeft as 1 on last day of month for Free Item coupon"                                          | 900058620     | 11111            | 00000               | "Beauty Club 2021" | "null"                            | "today"           | "null"                    | "D"                 | 30.0            | 30.00                    | "false"             | "false"                     | 0.00            | "WEB"   | "true"   | 000.00                   | 33333         | 00000                 | "null"        | "null"              | "null"                 | "null"           | "null"                 | "null"                  | "true"              | 1         | 12345             | "null"                      | "N"            | "N"    | 00000             | 00000                |
      | "As a BeautyClub Program member I want to see daysLeft as 29 on first day of month for Free Item coupon"                                        | 900058621     | 11111            | 00000               | "Beauty Club 2021" | "null"                            | "nextmonth"       | "null"                    | "D"                 | 30.0            | 29.50                    | "false"             | "null"                      | 0.50            | "WEB"   | "true"   | 000.00                   | 33333         | 00000                 | "null"        | "null"              | "null"                 | "null"           | "null"                 | "null"                  | "true"              | 29        | 12345             | "null"                      | "N"            | "Y"    | 00000             | 00000                |
      | "As a BeautyClub Program member I want to see daysLeft as 0 on last day of month for 10% coupon"                                                | 900058622     | 00000            | 22222               | "null"             | "10% Off EB Beauty Club campaign" | "null"            | "today"                   | "D"                 | 30.00           | 27.00                    | "false"             | "false"                     | 3.0             | "WEB"   | "true"   | 4.0                      | 00000         | 44444                 | "null"        | "null"              | "null"                 | "null"           | "null"                 | "null"                  | "true"              | 12345     | 0                 | "false"                     | "Y"            | "Y"    | 00000             | 00000                |
      | "As a BeautyClub Program member I want to see daysLeft as 13 on first day of month for 10% coupon"                                              | 900058623     | 00000            | 22222               | "null"             | "10% Off EB Beauty Club campaign" | "null"            | "2weeks"                  | "null"              | 000.00          | 000.00                   | "null"              | "false"                     | 000.00          | "WEB"   | "true"   | 8.0                      | 00000         | 44444                 | "null"        | "null"              | "null"                 | "null"           | "null"                 | "null"                  | "null"              | 12345     | 13                | "false"                     | "N"            | "Y"    | 00000             | 00000                |

  @Web @Mobile @POS @Smoke @Regression
  Scenario Outline: View Customer Beauty Club Details in DashBoard
    Given <scenario>
    And I use my Extra Card <xtra_card_nbr>
    When I view Beauty Club Details in DashBoard for my card
    Then I see the Beauty Club Rewards
    And I see my Beauty Club enrollment status as <enrolled>
    And I see my Beauty Club Free Item Campaign Id as <free_campaign_id> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Campaign WebDescription as <web_description> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Campaign End Date as <campaign_end_date> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Threshold Type Code as <threshold_type_code> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item First Threshold as <first_threshold> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Points required to get next coupon as <points_to_next_threshold> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Offer Limit Reached as <offer_limit_reached> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Points Progress as <points_progress> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item coupon number as <coupon_number> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Coupon loadable Indicator as <Free_Loadable> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Coupon loadActualDate as <Free_loadActualDate> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Coupon Redeemable Indicator as <free_Redeemable> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Coupon Redeemed Indicator as <free_Redeemed> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Coupon redeemActualDate as <free_redeemActualDate> <both_Campaigns> <earned>
    And I see my Beauty Club Free Coupon expire Date as <free_expireDt> <both_Campaigns> <earned>
    And I see my Beauty Club Free Coupon freeItemCoupon Flag as <freeItemCoupon_flag> <both_Campaigns> <earned>
    And I see my Beauty Club percent Campaign Id as <percent_campaign_id> <both_Campaigns> <earned>
    And I see my Beauty Club percent Campaign WebDescription <percent_web_description> <both_Campaigns> <earned>
    And I see my Beauty Club percent Campaign End Date as <percent_campaign_end_date> <both_Campaigns> <earned>
    And I see my Beauty Club percent Offer Limit Reached as <percent_offer_limit_reached> <both_Campaigns> <earned>
    And I see my Beauty Club percent extrabuckRewardsEarned as <extrabuck_rewards_earned> <both_Campaigns> <earned>
    And I see my Beauty Club percent Coupon loadable Indicator as <percent_Loadable> <both_Campaigns> <earned>
    And I see my Beauty Club percent Coupon loadActualDate as <percent_loadActualDate> <both_Campaigns> <earned>
    And I see my Beauty Club percent Coupon Issue Date as <percent_couponIssueDate> <both_Campaigns> <earned>
    And I see my Beauty Club percent Coupon freeItemCoupon Flag as <percent_freeItemCoupon_flag> <both_Campaigns> <earned>
    And I see my Beauty Club percent Coupon Redeemable Indicator as <percent_Redeemable> <both_Campaigns> <earned>
    And I see my Beauty Club percent Coupon Redeemed Indicator as <percent_Redeemed> <both_Campaigns> <earned>
    And I see my Beauty Club percent Coupon redeemActualDate as <percent_redeemActualDate> <both_Campaigns> <earned>
    And I see my Beauty Club percent Coupon expire Date as <percent_expireDt> <both_Campaigns> <earned>
    Examples:
      | scenario                                                                                                                                                               | xtra_card_nbr | free_campaign_id | percent_campaign_id | web_description    | percent_web_description           | campaign_end_date | percent_campaign_end_date | threshold_type_code | first_threshold | points_to_next_threshold | offer_limit_reached | percent_offer_limit_reached | points_progress | channel | enrolled | extrabuck_rewards_earned | coupon_number | percent_coupon_number | Free_Loadable | Free_loadActualDate | percent_Loadable | percent_loadActualDate | percent_couponIssueDate | freeItemCoupon_flag | percent_freeItemCoupon_flag | both_Campaigns | earned | free_Redeemable | percent_Redeemable | free_Redeemed | percent_Redeemed | free_redeemActualDate | percent_redeemActualDate | free_expireDt   | percent_expireDt |
      | "As a BeautyClub Program Member I want to see loadable, redeemable indicators as N when the print date expires"                                                        | 900058626     | 11111            | 22222               | "Beauty Club 2021" | "10% Off EB Beauty Club campaign" | "nextmonth"       | "2weeks"                  | "D"                 | 30.0            | 0.00                     | "true"              | "true"                      | 30.0            | "WEB"   | "true"   | 20.0                     | 33333         | 44444                 | "N"           | "null"              | "N"              | "null"                 | "today"                 | "true"              | "false"                     | "Y"            | "Y"    | "N"             | "N"                | "false"       | "false"          | "null"                | "null"                   | "printEndDate"  | "printEndDate"   |
      | "As a BeautyClub Program Member I want to see loadable, redeemable indicators as N when the redeem date expires"                                                       | 900058627     | 11111            | 22222               | "Beauty Club 2021" | "10% Off EB Beauty Club campaign" | "nextmonth"       | "2weeks"                  | "D"                 | 30.0            | 0.00                     | "true"              | "true"                      | 30.0            | "WEB"   | "true"   | 20.0                     | 33333         | 44444                 | "N"           | "null"              | "N"              | "null"                 | "today"                 | "true"              | "false"                     | "Y"            | "Y"    | "N"             | "N"                | "false"       | "false"          | "null"                | "null"                   | "redeemEndDate" | "redeemEndDate"  |
      | "As a BeautyClub Program Member I want to see redeemable Ind as N and redeemed Ind as Y when redeemActlDt is not null and coupon is present in redeemed_coupons table" | 900058628     | 11111            | 22222               | "Beauty Club 2021" | "10% Off EB Beauty Club campaign" | "nextmonth"       | "2weeks"                  | "D"                 | 30.0            | 0.00                     | "true"              | "true"                      | 30.0            | "WEB"   | "true"   | 20.0                     | 33333         | 44444                 | "N"           | "null"              | "N"              | "null"                 | "today"                 | "true"              | "false"                     | "Y"            | "Y"    | "N"             | "N"                | "true"        | "true"           | "today"               | "today"                  | "null"          | "null"           |
      | "As a BeautyClub Program member I want to see expiryDate same as printEndDate when coupon is not s2c for Free Item Coupon"                                             | 900058629     | 11111            | 00000               | "Beauty Club 2021" | "null"                            | "nextmonth"       | "null"                    | "D"                 | 30.0            | 0.00                     | "true"              | "null"                      | 30.0            | "WEB"   | "true"   | 000.00                   | 33333         | 00000                 | "N"           | "null"              | "null"           | "null"                 | "null"                  | "true"              | "null"                      | "Y"            | "Y"    | "N"             | "null"             | "false"       | "null"           | "null"                | "null"                   | "printEndDate"  | "null"           |
      | "As a BeautyClub Program member I want to see expiryDate same as redeemEndDate when after coupon s2c for Free Item Coupon"                                             | 900058630     | 11111            | 00000               | "Beauty Club 2021" | "null"                            | "nextmonth"       | "null"                    | "D"                 | 30.0            | 0.00                     | "true"              | "null"                      | 30.0            | "WEB"   | "true"   | 000.00                   | 33333         | 00000                 | "N"           | "null"              | "null"           | "null"                 | "null"                  | "true"              | "null"                      | "Y"            | "Y"    | "N"             | "null"             | "false"       | "null"           | "null"                | "null"                   | "redeemEndDate" | "null"           |
      | "As a BeautyClub Program member I want to see expiryDate same as printEndDate when coupon is not s2c for 10% Coupon"                                                   | 900058631     | 00000            | 22222               | "null"             | "10% Off EB Beauty Club campaign" | "null"            | "2weeks"                  | "null"              | 000.00          | 000.00                   | "null"              | "true"                      | 000.00          | "WEB"   | "true"   | 20.0                     | 00000         | 44444                 | "N"           | "null"              | "N"              | "null"                 | "today"                 | "true"              | "false"                     | "Y"            | "Y"    | "null"          | "N"                | "null"        | "false"          | "null"                | "null"                   | "null"          | "printEndDate"   |
      | "As a BeautyClub Program member I want to see expiryDate same as redeemEndDate when coupon after coupon s2c for 10% Coupon"                                            | 900058632     | 00000            | 22222               | "null"             | "10% Off EB Beauty Club campaign" | "null"            | "2weeks"                  | "null"              | 000.00          | 000.00                   | "null"              | "true"                      | 000.00          | "WEB"   | "true"   | 20.0                     | 00000         | 44444                 | "N"           | "null"              | "N"              | "null"                 | "today"                 | "true"              | "false"                     | "Y"            | "Y"    | "null"          | "N"                | "null"        | "false"          | "null"                | "null"                   | "null"          | "redeemEndDate"  |

  @Web @Mobile @POS @Smoke @Regression
  Scenario Outline: View Customer Beauty Club Details in DashBoard
    Given <scenario>
    And I use my Extra Card <xtra_card_nbr>
    When I view Beauty Club Details in DashBoard for my card
    Then I see the Beauty Club Rewards
    And I see my Beauty Club enrollment status as <enrolled>
    And I see my Beauty Club Free Item Campaign Id as <free_campaign_id> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Campaign WebDescription as <web_description> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Campaign End Date as <campaign_end_date> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Threshold Type Code as <threshold_type_code> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item First Threshold as <first_threshold> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Points required to get next coupon as <points_to_next_threshold> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Offer Limit Reached as <offer_limit_reached> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Points Progress as <points_progress> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item coupon number as <coupon_number> <both_Campaigns> <earned>
    And I see my Beauty Club Free Coupon freeItemCoupon Flag as <freeItemCoupon_flag> <both_Campaigns> <earned>
    And I see my Beauty Club percent Campaign Id as <percent_campaign_id> <both_Campaigns> <earned>
    And I see my Beauty Club percent Campaign WebDescription <percent_web_description> <both_Campaigns> <earned>
    And I see my Beauty Club percent Campaign End Date as <percent_campaign_end_date> <both_Campaigns> <earned>
    And I see my Beauty Club percent Offer Limit Reached as <percent_offer_limit_reached> <both_Campaigns> <earned>
    And I see my Beauty Club percent extrabuckRewardsEarned as <extrabuck_rewards_earned> <both_Campaigns> <earned>
    And I see my Beauty Club percent Coupon freeItemCoupon Flag as <percent_freeItemCoupon_flag> <both_Campaigns> <earned>
    Examples:
      | scenario                                                                                                        | xtra_card_nbr | free_campaign_id | percent_campaign_id | web_description | percent_web_description | campaign_end_date | percent_campaign_end_date | threshold_type_code | first_threshold | points_to_next_threshold | offer_limit_reached | percent_offer_limit_reached | points_progress | channel | enrolled | extrabuck_rewards_earned | coupon_number | percent_coupon_number | both_Campaigns | earned | freeItemCoupon_flag | percent_freeItemCoupon_flag |
      | "As a BeautyClub Program member I don't want to see free item and 10% Coupons when both Campaigns are Inactive" | 900058633     | 00000            | 00000               | "null"          | "null"                  | "null"            | "null"                    | "null"              | 000.00          | 000.00                   | "null"              | "null"                      | 000.00          | "WEB"   | "null"   | 000.00                   | 00000         | 00000                 | "N"            | "N"    | "null"              | "false"                     |
      | "As a BeautyClub Program member I don't want to see 10% Coupon when 10% Campaign is Inactive"                   | 900058634     | 00000            | 00000               | "null"          | "null"                  | "null"            | "null"                    | "null"              | 000.00          | 000.00                   | "null"              | "null"                      | 000.00          | "WEB"   | "null"   | 000.00                   | 00000         | 00000                 | "N"            | "N"    | "null"              | "false"                     |
      | "As a BeautyClub Program member I don't want to see Free Item Coupon when Free Item Campaign is Inactive"       | 900058635     | 00000            | 00000               | "null"          | "null"                  | "null"            | "null"                    | "null"              | 000.00          | 000.00                   | "null"              | "null"                      | 000.00          | "WEB"   | "null"   | 000.00                   | 00000         | 00000                 | "N"            | "N"    | "null"              | "false"                     |

  @Web @Mobile @POS @Smoke @Regression
  Scenario Outline: View Customer Beauty Club Details in DashBoard
    Given <scenario>
    And I use my Extra Card <xtra_card_nbr>
    When I view Beauty Club Details in DashBoard for my card
    Then I see the Beauty Club Rewards
    And I see my Beauty Club enrollment status as <enrolled>
    And I see only one Free Item Campagin and one percent Campaign <campaigns_count> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Campaign Id as <free_campaign_id> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Campaign WebDescription as <web_description> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Campaign End Date as <campaign_end_date> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Threshold Type Code as <threshold_type_code> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item First Threshold as <first_threshold> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Points required to get next coupon as <points_to_next_threshold> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Offer Limit Reached as <offer_limit_reached> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Points Progress as <points_progress> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item coupon number as <coupon_number> <both_Campaigns> <earned>
    And I see my Beauty Club Free Coupon freeItemCoupon Flag as <freeItemCoupon_flag> <both_Campaigns> <earned>
    And I see my Beauty Club Free Coupon expire Date as <free_expireDt> <both_Campaigns> <earned>
    And I see my Beauty Club percent Campaign Id as <percent_campaign_id> <both_Campaigns> <earned>
    And I see my Beauty Club percent Campaign WebDescription <percent_web_description> <both_Campaigns> <earned>
    And I see my Beauty Club percent Campaign End Date as <percent_campaign_end_date> <both_Campaigns> <earned>
    And I see my Beauty Club percent Offer Limit Reached as <percent_offer_limit_reached> <both_Campaigns> <earned>
    And I see my Beauty Club percent extrabuckRewardsEarned as <extrabuck_rewards_earned> <both_Campaigns> <earned>
    And I see my Beauty Club percent Coupon freeItemCoupon Flag as <percent_freeItemCoupon_flag> <both_Campaigns> <earned>
    And I see my Beauty Club percent Coupon expire Date as <percent_expireDt> <both_Campaigns> <earned>
    Examples:
      | scenario                                                                                                                     | xtra_card_nbr | free_campaign_id | percent_campaign_id | web_description    | percent_web_description           | campaign_end_date | percent_campaign_end_date | threshold_type_code | first_threshold | points_to_next_threshold | offer_limit_reached | percent_offer_limit_reached | points_progress | channel | enrolled | extrabuck_rewards_earned | coupon_number | percent_coupon_number | both_Campaigns | earned | freeItemCoupon_flag | percent_freeItemCoupon_flag | free_expireDt   | percent_expireDt | campaigns_count |
      | "As a BeautyClub Program member I don't want to see more than one free item and 10% Coupons at a time"                       | 900058636     | 11111            | 22222               | "Beauty Club 2021" | "10% Off EB Beauty Club campaign" | "nextmonth"       | "2weeks"                  | "D"                 | 30.0            | 0.00                     | "true"              | "true"                      | 30.0            | "WEB"   | "true"   | 20.0                     | 33333         | 44444                 | "Y"            | "Y"    | "true"              | "false"                     | "null"          | "null"           | 2               |
      | "As a BeautyClub Program member I want to see expiryDate same as redeemEndDate after coupon is s2c for both the Campaigns"   | 900058637     | 11111            | 22222               | "Beauty Club 2021" | "10% Off EB Beauty Club campaign" | "nextmonth"       | "2weeks"                  | "D"                 | 30.0            | 0.00                     | "true"              | "true"                      | 30.0            | "WEB"   | "true"   | 20.0                     | 33333         | 44444                 | "Y"            | "Y"    | "true"              | "false"                     | "printEndDate"  | "printEndDate"   | 2               |
      | "As a BeautyClub Program member I want to see expiryDate same as printEndDate when coupon is not s2c for both the Campaigns" | 900058638     | 11111            | 22222               | "Beauty Club 2021" | "10% Off EB Beauty Club campaign" | "nextmonth"       | "2weeks"                  | "D"                 | 30.0            | 0.00                     | "true"              | "true"                      | 30.0            | "WEB"   | "true"   | 20.0                     | 33333         | 44444                 | "Y"            | "Y"    | "true"              | "false"                     | "redeemEndDate" | "redeemEndDate"  | 2               |

  @Web @Mobile @POS @Smoke @Regression
  Scenario Outline: View Customer Beauty Club Details in DashBoard
    Given <scenario>
    And I use my Extra Card <xtra_card_nbr>
    When I view Beauty Club Details in DashBoard for my card
    Then I see the Beauty Club Rewards
    And I see my Beauty Club enrollment status as <enrolled>
    And I see my Beauty Club Free Item Campaign Id as <free_campaign_id> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Campaign WebDescription as <web_description> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Campaign End Date as <campaign_end_date> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Threshold Type Code as <threshold_type_code> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item First Threshold as <first_threshold> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Points required to get next coupon as <points_to_next_threshold> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Offer Limit Reached as <offer_limit_reached> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item Points Progress as <points_progress> <both_Campaigns> <earned>
    And I see my Beauty Club Free Item coupon number as <coupon_number> <both_Campaigns> <earned>
    And I see my Beauty Club Free Coupon freeItemCoupon Flag as <freeItemCoupon_flag> <both_Campaigns> <earned>
    And I see my Beauty Club Free Coupon expire Date as <free_expireDt> <both_Campaigns> <earned>
    And I see my Beauty Club percent Campaign Id as <percent_campaign_id> <both_Campaigns> <earned>
    And I see my Beauty Club percent Campaign WebDescription <percent_web_description> <both_Campaigns> <earned>
    And I see my Beauty Club percent Campaign End Date as <percent_campaign_end_date> <both_Campaigns> <earned>
    And I see my Beauty Club percent Offer Limit Reached as <percent_offer_limit_reached> <both_Campaigns> <earned>
    And I see my Beauty Club percent extrabuckRewardsEarned as <extrabuck_rewards_earned> <both_Campaigns> <earned>
    And I see my Beauty Club percent Coupon freeItemCoupon Flag as <percent_freeItemCoupon_flag> <both_Campaigns> <earned>
    And I see my Beauty Club percent Coupon expire Date as <percent_expireDt> <both_Campaigns> <earned>
    Examples:
      | scenario                                                                                                                                                                                | xtra_card_nbr | free_campaign_id | percent_campaign_id | web_description    | percent_web_description           | campaign_end_date | percent_campaign_end_date | threshold_type_code | first_threshold | points_to_next_threshold | offer_limit_reached | percent_offer_limit_reached | points_progress | channel | enrolled | extrabuck_rewards_earned | coupon_number | percent_coupon_number | both_Campaigns | earned | freeItemCoupon_flag | percent_freeItemCoupon_flag | free_expireDt   | percent_expireDt |
      | "As a BeautyClub Program member I spend on Beauty products and reached limit and redeemed on 1st day of the month and want to see Redeem Expire Date"                                   | 900058639     | 11111            | 22222               | "Beauty Club 2021" | "10% Off EB Beauty Club campaign" | "nextmonth"       | "2weeks"                  | "D"                 | 30.0            | 0.00                     | "true"              | "true"                      | 30.0            | "WEB"   | "true"   | 20.0                     | 33333         | 44444                 | "Y"            | "Y"    | "true"              | "false"                     | "redeemEndDate" | "redeemEndDate"  |
      | "As a BeautyClub Program member I spend on Beauty products and reached limit and redeemed on 14th day of the month and want to see Redeem Expire Date"                                  | 900058640     | 11111            | 22222               | "Beauty Club 2021" | "10% Off EB Beauty Club campaign" | "nextmonth"       | "2weeks"                  | "D"                 | 30.0            | 0.00                     | "true"              | "true"                      | 30.0            | "WEB"   | "true"   | 20.0                     | 33333         | 44444                 | "Y"            | "Y"    | "true"              | "false"                     | "redeemEndDate" | "redeemEndDate"  |
      | "As a BeautyClub Program member I spend on Beauty products and reached limit and redeemed at 11:59PM on lastday-2 of the month and want to see Free Item and 10% Coupons"               | 900058641     | 11111            | 22222               | "Beauty Club 2021" | "10% Off EB Beauty Club campaign" | "nextmonth"       | "2weeks"                  | "D"                 | 30.0            | 0.00                     | "true"              | "true"                      | 30.0            | "WEB"   | "true"   | 20.0                     | 33333         | 44444                 | "Y"            | "Y"    | "true"              | "false"                     | "redeemEndDate" | "redeemEndDate"  |
      | "As a BeautyClub Program member I redeemed at 11:59PM on last day of the month and want to see Free Item Coupon and 10% Coupon"                                                         | 900058645     | 11111            | 22222               | "Beauty Club 2021" | "10% Off EB Beauty Club campaign" | "nextmonth"       | "2weeks"                  | "D"                 | 30.0            | 0.00                     | "true"              | "true"                      | 30.0            | "WEB"   | "true"   | 20.0                     | 33333         | 44444                 | "Y"            | "Y"    | "true"              | "false"                     | "redeemEndDate" | "redeemEndDate"  |
      | "As a BeautyClub Program member I spend on Beauty products and haven't reached limit at 11:59PM on last day of the month and don't want to see Free Item Coupon but can see 10% coupon" | 900058642     | 11111            | 22222               | "Beauty Club 2021" | "10% Off EB Beauty Club campaign" | "nextmonth"       | "2weeks"                  | "D"                 | 30.0            | 10.00                    | "true"              | "true"                      | 20.0            | "WEB"   | "true"   | 20.0                     | 00000         | 44444                 | "Y"            | "Y"    | "true"              | "false"                     | "null"          | "null"           |
      | "As a BeautyClub Program member I spend on Beauty products and reached limit and redeemed at 12:00AM on last day of the redeem expire date and want to see Free Item and 10% Coupon"    | 900058644     | 11111            | 22222               | "Beauty Club 2021" | "10% Off EB Beauty Club campaign" | "nextmonth"       | "2weeks"                  | "D"                 | 30.0            | 0.00                     | "true"              | "true"                      | 30.0            | "WEB"   | "true"   | 20.0                     | 33333         | 44444                 | "Y"            | "Y"    | "true"              | "false"                     | "redeemEndDate" | "redeemEndDate"  |

  @Web @Mobile @POS @Smoke @Regression
  Scenario Outline: View Customer Beauty Club Details in DashBoard
    Given <scenario>
    And I use my Extra Card <xtra_card_nbr>
    When I view Beauty Club Details in DashBoard for my card
    Then I do not see the Beauty Club Rewards
    And I see my Error Message as <error_message>
    Examples:
      | scenario                                                           | xtra_card_nbr | error_message      |
      | "Am not a ExtraCard member and want to see Card Not on File Error" | 900058649     | "Card Not on File" |
      | "Am a Hot Card member and want to see Hot Card Error"              | 900058650     | "HOT XC Card"      |


  #@Web @Mobile @POS @Smoke @Regression
  #Scenario Outline: View Customer Beauty Club Details in DashBoard
  #  Given <scenario>
  #  And I use my Extra Card <xtra_card_nbr>
  #  When I view Beauty Club Details in DashBoard for my card
  #  Then I see the Beauty Club Rewards
  #  And I see my Beauty Club enrollment status as <enrolled>
  #  And I see my Beauty Club Default Campaign Id as <campaign_id>
  #  And I see my Beauty Club <web_description>
  #  And I see my Beauty Club Campaign End Date as <campaign_end_date>
  #  And I see my Beauty Club Threshold Type Code as <threshold_type_code>
  #  And I see my Beauty Club First Threshold as <first_threshold>
  #  And I see my Beauty Club Points required to get next coupon as <points_to_next_threshold>
  #  And I see my Beauty Club Offer Limit Reached as <offer_limit_reached>
  #  And I see my Beauty Club Points Progress as <points_progress>
  #  And I see my Beauty Club  Reward Amount as <reward_amount>
  #  Examples:
  #    | scenario                                                                                                                         | xtra_card_nbr | campaign_id | web_description    | campaign_end_date | threshold_type_code | first_threshold | points_to_next_threshold | reward_amount | offer_limit_reached | points_progress | channel | enrolled |
  #    | "Am not a BeautyClub Program member and I don't want to see Free Item Coupon and CpnNbr but want to see default response"        | 900058651     | "44498"     | "Beauty Club 2021" | "2021-12-31"      | "D"                 | 30.0            | 30.0                     | 3.0           | "false"             | 0.00            | "WEB"   | "false"  |
  #    | "I have unenrolled from BeautyClub Program and I don't want to see Free Item Coupon and CpnNbr but want to see default response" | 900058652     | "44498"     | "Beauty Club 2021" | "2021-12-31"      | "D"                 | 30.0            | 30.0                     | 3.0           | "false"             | 0.00            | "WEB"   | "false"  |